### ISSUE TITLE
Can't read .rle files

### ISSUE THREAD

**Issue by emilwallner** [GOLAI/game#1]
<img width="818" alt="screen shot 2018-07-05 at 2 38 17 pm" src="https://user-images.githubusercontent.com/12543699/42323652-289420ca-8061-11e8-87a5-1862b2705f78.png">

**Two test players attached:**
[spacefiller.txt](https://github.com/GOLAI/game/files/2166568/spacefiller.txt)
[2.txt](https://github.com/GOLAI/game/files/2166570/2.txt)

**Comment by amarzial** [comment]
You have a multiple '$' or an '$' before the '!' in the file.
the symbol '$' should follow the same rules of 'b' and 'o'
i.e. line -> 2obo4b2$ :notice the "2$", that means: "after this line there is an empty one"

From 76d4c7b a better exception is raised
